name: "Bug Report"
description: "报告一个错误或异常行为"
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **请仔细填写以下信息，以便更快定位问题！**
  - type: textarea
    id: description
    attributes:
      label: "问题描述"
      description: "请清晰描述你遇到的问题"
      placeholder: "例如：输入某个参数后程序异常退出且未返回结果"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "如何复现？"
      description: "如何复现这个问题？"
      placeholder: |
        1. 第一步操作
        2. 第二步操作
        3. 出现错误
  - type: textarea
    id: expected
    attributes:
      label: "上传证据"
      description: "在此处上传错误日志/屏幕截图/屏幕录制内容"
  - type: textarea
    id: actual
    attributes:
      label: "你的信息"
      description: "请提供一些信息，方便我们解决该问题"
      placeholder: |
        1. Windows版本
        2. BeaconEX版本
        3. 运行BeaconEX的计算机已经连接到Internet
        4. BeaconEX不是远古版
  - type: checkboxes
    id: checks
    attributes:
      label: "确认项"
      options:
        - label: "我已尝试重启终端"
        - label: "我已尝试重启计算机"
        - label: "我已尝试重新安装BeaconEX"
