name: "Bug Report"
description: "报告一个错误或异常行为"
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **请仔细填写以下信息，以便更快定位问题！**
  - type: textarea
    id: description
    attributes:
      label: "问题描述"
      description: "请清晰描述你遇到的问题"
      placeholder: "例如：输入某个参数后程序异常退出且未返回结果"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "重现步骤"
      description: "如何复现这个问题？"
      placeholder: |
        1. 第一步操作
        2. 第二步操作
        3. 出现错误
  - type: textarea
    id: expected
    attributes:
      label: "预期行为"
      description: "你期望的正确结果是什么？"
  - type: textarea
    id: actual
    attributes:
      label: "实际行为"
      description: "实际发生了什么？"
  - type: dropdown
    id: os
    attributes:
      label: "Windows版本"
      options:
        - "Windows 7"
        - "Windows 8/8.1"
        - "Windows 10"
        - "Windows 11"
  - type: checkboxes
    id: checks
    attributes:
      label: "确认项"
      options:
        - label: "我已查阅相关文档"
          required: true
        - label: "我已尝试重启应用"
