name: "Bug Report"
description: "报告一个错误或异常行为"
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **请仔细填写以下信息，以便更快定位问题！**
  - type: textarea
    id: description
    attributes:
      label: "问题描述"
      description: "请清晰描述你遇到的问题"
      placeholder: "例如：输入某个参数后程序异常退出且未返回结果"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: "如何复现？"
      description: "如何复现这个问题？"
      placeholder: |
        1. 第一步你做什麽了
        2. 第二步你做什麽了
        ......
        出現錯誤：錯誤
  - type: textarea
    id: expected
    attributes:
      label: "上传证据"
      description: "在此处上传错误日志/屏幕截图/屏幕录制内容"
    - type: input
    id: contact
    attributes:
      label: 系統版本
      description: 請在此填入你的Windows系統版本
      placeholder: 例如：Windows10 22H2
    validations:
      required: false      
  - type: checkboxes
    id: checks
    attributes:
      label: "請確認以下信息："
      options:
        - label: "我已尝试重启终端"
        - label: "我已尝试重启计算机"
        - label: "我已尝试重新安装BeaconEX"
